# Generated by Django 2.2.24 on 2023-12-10 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_adoptante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoptante', to=settings.AUTH_USER_MODEL),
        ),
    ]
