# Generated by Django 2.2.24 on 2023-12-10 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_auto_20231210_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_donante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id_veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinario', to=settings.AUTH_USER_MODEL),
        ),
    ]
