# Generated by Django 2.2.24 on 2023-12-10 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinaria', '0003_auto_20231210_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chequeo',
            field=models.DateField(default='2023-12-04'),
        ),
        migrations.CreateModel(
            name='FormularioAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_de_miembros_familia', models.IntegerField()),
                ('tiene_otros_animales', models.BooleanField(default=False)),
                ('pregunta1', models.CharField(choices=[('1 a 2 veces al dia', '1 a 2 veces al dia'), ('2 o 3 veces al dia', '2 o 3 veces al dia'), ('Mas de tres veces', 'Mas de tres veces'), ('No aplica', 'No aplica')], max_length=50)),
                ('pregunta2', models.CharField(choices=[('1 vez a la semana', '1 vez a la semana'), ('1 a 3 veces a la semana', '1 a 3 veces a la semana'), ('Mas de 3 veces a la semana', 'Mas de 3 veces a la semana')], max_length=50)),
                ('pregunta3', models.CharField(choices=[('Comida seca especial para mascotas', 'Comida seca especial para mascotas'), ('Comida seca y comida casera', 'Comida seca y comida casera'), ('comida casera', 'comida casera'), ('No aplica', 'No aplica')], max_length=50)),
                ('pregunta4', models.CharField(choices=[('De 1 a 3 veces al mes', 'De 1 a 3 veces al mes'), ('De 1 a 3 veces cada 2 meses', 'De 1 a 3 veces cada 2 meses'), ('Cada vez que tenga olor fuerte', 'Cada vez que tenga olor fuerte')], max_length=50)),
                ('pregunta5', models.CharField(choices=[('De 1 a 3 veces cada 2 meses', 'De 1 a 3 veces cada 2 meses'), ('1 vez por mes', '1 vez por mes'), ('1 vez por semana', '1 vez por semana')], max_length=50)),
                ('descripcion_casa', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='veterinaria.Mascota')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
