# Generated by Django 2.2.24 on 2023-12-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_auto_20231210_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadopcion',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='veterinaria.Mascota'),
        ),
    ]
